apiVersion: v1
kind: Service
metadata:
  name: ecoverify-api
  namespace: ecoverify

spec:
  type: ClusterIP

  ports:
  - name: ecoverify-api
    port: 3000
    targetPort: ecoverify-api
  - name: debug
    port: 4000
    targetPort: debug
