apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/ecoverify/
patches:
- path: ./dev-ecoverify-patch-deploy.yaml
- path: ./dev-ecoverify-patch-service.yaml
images:
- name: service-image
  newName: syedhyder1362k/service/ecoverify-api
  newTag: 0.0.1
