apiVersion: v1
kind: Namespace
metadata:
  name: ecoverify

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoverify
  namespace: ecoverify

spec:
  selector:
    matchLabels:
      app: ecoverify

  template:
    metadata:
      labels:
        app: ecoverify

    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: init-migrate
        image: service-image
        command: ['./ecoverify-admin']
        env:
        - name: ECOVERIFY_DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_user
              optional: true
        - name: ECOVERIFY_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_password
              optional: true
        - name: ECOVERIFY_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
              optional: true
        - name: ECOVERIFY_DB_DISABLE_TLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_disabletls
              optional: true
      
      containers:
      - name: ecoverify-api
        image: service-image

        ports:
        - name: ecoverify-api
          containerPort: 3000
        - name: debug
          containerPort: 4000
        
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /v1/readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /v1/liveness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: ecoverify-api
  namespace: ecoverify

spec:
  selector:
    app: ecoverify
